label: [diffusion_ard] # [random, diffusion_ard, local_search, dfs, bfs] #[polynomial, polynomial_suminverse, diffusion, diffusion_ard, local_search, random, bfs, dfs]
save_dir: ./logs/May16/
n_exp: 7 # number of experiments with different random seeds
bo_settings:
  batch_size: 1 # batch size
  max_iters: 300 # number of total queries
  max_radius: 5 # the maximum hop distance to the centre node when constructing the local context graph
  n_init: 1 # Initial queried points 
  Q: 4000 # the size of the context ComboSubgraph
  large_Q: False
  exploitation: False
  start_location: random #[random, ei, betweenness, degree] # the initial starting location of search, recommended for large k
  restart_location: queried_best #[same_as_start, queried_best]
  tr_settings:    # settings related to the trust region on the graph search space
    n_nodes_min: 10         # the min number of nodes in the trust region
    trust_region_multiplier: 1.5 
    succ_tol: 10       # success tolerance
    fail_tol: 30      # fail tolerance
    shrink_tol: 10       # shrink tolerance
problem_name: influence_maximisation # [centrality, epidemic, influence_maximisation] the experimental problem type
problem_settings:  
  k: 32 # number of combinations
  graph_type: CS # [ws, ba, "contact_network_day1", "contact_network_day2", CS, Facebook]
  underlying_function: "independent_cascading" # ["betweenness_centrality", "eigenvector_centrality", "infection_time", "independent_cascading"]
  IC_p: 0.05
  IC_n_samples: 1000
