label: ["polynomial", "polynomial_suminverse", "diffusion", "diffusion_ard", "random", "local_search", "bfs", "dfs"]
save_dir: ./logs/testing/
n_exp: 50 # number of experiments with different random seeds
bo_settings:
  batch_size: 1 # batch size
  max_iters: 1000 # number of total queries
  max_radius: 10 # the maximum hop distance to the centre node when constructing the local context graph
  Q: 2000 # the size of the context ComboSubgraph
  tr_settings:    # settings related to the trust region on the graph search space
    n_nodes_min: 10         # the min number of nodes in the trust region
    trust_region_multiplier: 1.5 
    succ_tol: 10       # success tolerance
    fail_tol: 30      # fail tolerance
problem_name: centrality # the experimental problem type
problem_settings:
  n: 1000 # number of nodes in the underlying (synthetic) random graphs
  k: 4 # number of combinations
  graph_type: "ba" # "ws", "ba"
  underlying_function: "eigenvector_centrality" # "betweenness_centrality" "eigenvector_centrality"
  n_init: 10 # Initial queried points 
  m: 3
  wsk: 30
  p: 0.2
