label: [diffusion_ard] # [diffusion_ard, local_search, dfs, bfs, random] #[polynomial, polynomial_suminverse, diffusion, diffusion_ard, local_search, random, bfs, dfs]
save_dir: ./logs/May15/
n_exp: 5 # number of experiments with different random seeds
bo_settings:
  batch_size: 1 # batch size
  max_iters: 300 # number of total queries
  max_radius: 10 # the maximum hop distance to the centre node when constructing the local context graph
  n_init: 30 # Initial queried points 
  Q: 4000 # the size of the context ComboSubgraph
  large_Q: False
  exploitation: False
  start_location: random # the initial starting location of search, recommended for large k
  restart_location: queried_best #[same_as_start, queried_best]
  tr_settings: # settings related to the trust region on the graph search space
    n_nodes_min: 10 # the min number of nodes in the trust region
    trust_region_multiplier: 1.5 
    succ_tol: 10 # success tolerance
    fail_tol: 30 # fail tolerance
    shrink_tol: 10       # shrink tolerance
problem_name: resilience # the experimental problem type
problem_settings:  
  graph_type: Road 
  k: 8 # number of combinations
  underlying_function: transitivity
